pipeline {
    agent any

    environment {
        // Переконайся, що в Jenkins додано Credentials з таким ID
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
        
        // НАЛАШТУВАННЯ БАЗИ
        DB_HOST = 'postgres' 
        DB_PORT = '5432'
        DB_NAME = 'mydatabase' 
        DB_USER = "${env.POSTGRES_SECRET_USR}"
        DB_PASS = "${env.POSTGRES_SECRET_PSW}"
        
        PYTHONPATH = "${env.WORKSPACE}/PyTest DQ Framework"
    }

    stages {
        stage('Prepare and Run Tests') {
            steps {
                dir('PyTest DQ Framework') {
                    sh '''
                        # 1. Створення та активація venv
                        python3 -m venv venv
                        . venv/bin/activate
                        
                        # 2. Оновлення та встановлення всіх бібліотек (включаючи dotenv)
                        pip install --upgrade pip
                        pip install pytest pytest-html pandas pyarrow sqlalchemy psycopg2-binary python-dotenv
                        
                        # 3. Встановлення з requirements.txt, якщо він є
                        if [ -f requirements.txt ]; then
                            pip install -r requirements.txt
                        fi
                        
                        # 4. Створення папки для звіту
                        mkdir -p reports
                        
                        # 5. 
                        python3 -m pytest tests -m "parquet_data or example" \
                        --html=reports/dq_report.html \
                        --self-contained-html
                    '''
                }
            }
        }
    }

    post {
        always {
            dir('PyTest DQ Framework') {
                archiveArtifacts artifacts: 'reports/*.html', allowEmptyArchive: true
                echo "Звіт згенеровано. Перевір вкладку Artifacts у Jenkins."
            }
        }
    }
}