[pytest]
# Шаблони для пошуку тестів
python_files = test_*
python_functions = test_*
python_classes = Test*

# Реєстрація маркерів (щоб прибрати UnknownMarkWarning)
markers =
    parquet_files: валідація даних у Parquet файлах
    db_checks: тести для перевірки PostgreSQL
    dq_check: загальні перевірки якості даних
    example: marks example tests
    parquet_data: marks tests for parquet data
    reconciliation: тести на зіставлення даних між Postgres та Parquet
    facility_min: тести для таблиці facility_name_min_time_spent
    facility_avg: тести для таблиці facility_type_avg_time_spent
    patient_sum: тести для таблиці patient_sum_treatment_cost

# Налаштування параметрів запуску за замовчуванням
addopts = 
    -v 
    -s
    --html=reports/dq_report.html 
    --self-contained-html